import type { HourLog } from "./types";

const STUDENT_ID = "dev-student_nhs_beta";

/** Local demo content used until Supabase credentials are configured. */
export const SEED_HOUR_LOGS: HourLog[] = [
  {
    id: "log-seed-food-pantry",
    studentId: STUDENT_ID,
    studentName: "Avery Chen",
    opportunityId: "seed-nhs-food-pantry",
    activityTitle: "Food Pantry Sort & Pack",
    honorSociety: "NHS",
    serviceDate: "2026-08-22T14:00:00.000Z",
    hoursLogged: 2.5,
    reflectionText:
      "Sorted produce donations and packed 60 weekend bags with the Saturday crew.",
    proofPhotoUrl: null,
    supervisorName: "Dana Whitfield",
    supervisorEmail: "dana@lakesidefoodbank.org",
    supervisorPhone: "704-555-0142",
    supervisorConfirmed: true,
    status: "verified",
    reviewNotes: null,
    reviewedAt: "2026-08-24T15:00:00.000Z",
    createdAt: "2026-08-23T13:00:00.000Z",
  },
  {
    id: "log-seed-book-fair",
    studentId: STUDENT_ID,
    studentName: "Avery Chen",
    opportunityId: "seed-book-fair",
    activityTitle: "Library Book Fair Setup",
    honorSociety: null,
    serviceDate: "2026-08-28T20:00:00.000Z",
    hoursLogged: 1.5,
    reflectionText: "Unpacked and shelved four crates of new titles.",
    proofPhotoUrl: null,
    supervisorName: "Ms. Holloway",
    supervisorEmail: "j.holloway@pinelakeprep.org",
    supervisorPhone: null,
    supervisorConfirmed: true,
    status: "verified",
    reviewNotes: null,
    reviewedAt: "2026-08-30T14:30:00.000Z",
    createdAt: "2026-08-29T12:10:00.000Z",
  },
  {
    id: "log-seed-beta-bingo",
    studentId: STUDENT_ID,
    studentName: "Avery Chen",
    opportunityId: "seed-beta-senior-center",
    activityTitle: "Senior Center Bingo Night",
    honorSociety: "Beta Club",
    serviceDate: "2026-09-01T22:30:00.000Z",
    hoursLogged: 2,
    reflectionText:
      "Called numbers and sat with residents at table four for the whole session.",
    proofPhotoUrl: "https://example.org/proof/bingo-night.jpg",
    supervisorName: "Rosa Delgado",
    supervisorEmail: "rdelgado@pinelakeseniorliving.org",
    supervisorPhone: "704-555-0188",
    supervisorConfirmed: false,
    status: "pending",
    reviewNotes: null,
    reviewedAt: null,
    createdAt: "2026-09-02T11:45:00.000Z",
  },
  {
    id: "log-seed-manual-shoreline",
    studentId: STUDENT_ID,
    studentName: "Avery Chen",
    opportunityId: null,
    activityTitle: "Neighborhood shoreline cleanup (self-organized)",
    honorSociety: "NHS",
    serviceDate: "2026-09-05T14:00:00.000Z",
    hoursLogged: 3,
    reflectionText:
      "Organized six neighbors to clear litter from the cove. Filled nine bags.",
    proofPhotoUrl: "https://example.org/proof/shoreline.jpg",
    supervisorName: "Marcus Webb",
    supervisorEmail: "mwebb@lakenormanhoa.org",
    supervisorPhone: "704-555-0119",
    supervisorConfirmed: false,
    status: "pending",
    reviewNotes: null,
    reviewedAt: null,
    createdAt: "2026-09-06T15:30:00.000Z",
  },
  {
    id: "log-seed-rejected-babysitting",
    studentId: STUDENT_ID,
    studentName: "Avery Chen",
    opportunityId: null,
    activityTitle: "Babysitting for a family friend",
    honorSociety: null,
    serviceDate: "2026-08-15T23:00:00.000Z",
    hoursLogged: 4,
    reflectionText: "Watched two children for the evening.",
    proofPhotoUrl: null,
    supervisorName: "Karen Liu",
    supervisorEmail: "karen.liu@example.com",
    supervisorPhone: null,
    supervisorConfirmed: false,
    status: "rejected",
    reviewNotes:
      "Paid or personal childcare does not qualify as community service. Try a partner organization from the task feed.",
    reviewedAt: "2026-08-17T13:20:00.000Z",
    createdAt: "2026-08-16T18:00:00.000Z",
  },
  {
    id: "log-seed-bella-tutoring",
    studentId: "student-bella-ortiz",
    studentName: "Bella Ortiz",
    opportunityId: "seed-spanish-tutoring",
    activityTitle: "Spanish I Study Hall Support",
    honorSociety: "Spanish Honor Society",
    serviceDate: "2026-09-04T14:45:00.000Z",
    hoursLogged: 1,
    reflectionText: "Ran conversation drills with four Spanish I students.",
    proofPhotoUrl: null,
    supervisorName: "Sr. Alvarez",
    supervisorEmail: "m.alvarez@pinelakeprep.org",
    supervisorPhone: null,
    supervisorConfirmed: false,
    status: "pending",
    reviewNotes: null,
    reviewedAt: null,
    createdAt: "2026-09-04T20:00:00.000Z",
  },
  {
    id: "log-seed-caleb-supplies",
    studentId: "student-caleb-nguyen",
    studentName: "Caleb Nguyen",
    opportunityId: "seed-njhs-supply-drive",
    activityTitle: "Middle School Supply Drive Sorting",
    honorSociety: "NJHS",
    serviceDate: "2026-09-03T19:30:00.000Z",
    hoursLogged: 1,
    reflectionText: "Counted and boxed donated notebooks for the supply closet.",
    proofPhotoUrl: null,
    supervisorName: "Ms. Rivera",
    supervisorEmail: "m.rivera@pinelakeprep.org",
    supervisorPhone: null,
    supervisorConfirmed: false,
    status: "pending",
    reviewNotes: null,
    reviewedAt: null,
    createdAt: "2026-09-03T22:15:00.000Z",
  },
  {
    id: "log-seed-dara-stem",
    studentId: "student-dara-patel",
    studentName: "Dara Patel",
    opportunityId: null,
    activityTitle: "Robotics club outreach at the public library",
    honorSociety: "Science National Honor Society",
    serviceDate: "2026-09-06T18:00:00.000Z",
    hoursLogged: 2.5,
    reflectionText:
      "Ran a build-a-bot table for elementary visitors during the library open house.",
    proofPhotoUrl: "https://example.org/proof/robotics-table.jpg",
    supervisorName: "Priya Raman",
    supervisorEmail: "praman@lakenormanlibrary.org",
    supervisorPhone: "704-555-0173",
    supervisorConfirmed: false,
    status: "pending",
    reviewNotes: null,
    reviewedAt: null,
    createdAt: "2026-09-07T09:20:00.000Z",
  },
];
